//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.17.0
//     from Assets/!MyProject/Actions/HeroMovement.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/!MyProject/Actions/HeroMovement.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @HeroMovement: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @HeroMovement()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""HeroMovement"",
    ""maps"": [
        {
            ""name"": ""HeroesController"",
            ""id"": ""83b9a61b-fb76-49f7-89fd-5db021798520"",
            ""actions"": [
                {
                    ""name"": ""MovementPlayerBase"",
                    ""type"": ""Value"",
                    ""id"": ""3334b5ea-6d5d-4184-896d-14eaef180c0c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JumpPlayerBase"",
                    ""type"": ""Button"",
                    ""id"": ""514ea833-da1b-489b-a5e5-5f8210f0f6c9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""9e8f6d45-31f5-4934-bf0a-9019fa2a6a52"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementPlayerBase"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f78d617d-cb83-4e6a-ac7c-6aae8b242268"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboarding"",
                    ""action"": ""MovementPlayerBase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""da275061-820e-4f0d-b6eb-5f6e66e99028"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboarding"",
                    ""action"": ""MovementPlayerBase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""437ce38f-88da-4be1-95ea-016800ce2271"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboarding"",
                    ""action"": ""MovementPlayerBase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""afaea216-8990-4206-9498-63fc2d6612a2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboarding"",
                    ""action"": ""MovementPlayerBase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f574e4d3-8b43-4838-a1e4-96fe68b5e91e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboarding"",
                    ""action"": ""JumpPlayerBase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CarController"",
            ""id"": ""31f9b62e-30d4-44af-88fa-58f6860a68d3"",
            ""actions"": [
                {
                    ""name"": ""CarMovementBase"",
                    ""type"": ""Value"",
                    ""id"": ""54e29b31-e092-4f51-8c6b-b1e49ec44f58"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""886d597a-b6ee-432c-aa31-4dec7ed097e7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""95a3ae1e-1b51-4668-a9e3-9ad2fe4499ea"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CarMovementBase"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2e2889f2-34a9-4133-97ee-0d8674b0976f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";CarKeyboard"",
                    ""action"": ""CarMovementBase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7bc1325c-c443-4e1b-9968-8f7a36254efb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";CarKeyboard"",
                    ""action"": ""CarMovementBase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1fd4a662-e126-47b0-8d03-3bb7ee40e212"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";CarKeyboard"",
                    ""action"": ""CarMovementBase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f5685a02-dab3-40ae-b420-e2bab33fbb78"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";CarKeyboard"",
                    ""action"": ""CarMovementBase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""66033610-4206-4d45-b485-e8dd84483d2c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";CarKeyboard"",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CameraController"",
            ""id"": ""c1260626-e7a1-4b76-8487-0691640d3fa4"",
            ""actions"": [
                {
                    ""name"": ""CameraLook"",
                    ""type"": ""Value"",
                    ""id"": ""c23c6bc1-11c3-45f8-818a-5c7efddf228f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""04b15718-01c5-459d-800a-b159809c1829"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""24f63829-c6cc-46e8-b131-858c653a7989"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";CameraController"",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4746ac08-dea1-4ab9-accd-cce7467e9840"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";CameraController"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboarding"",
            ""bindingGroup"": ""Keyboarding"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""CarKeyboard"",
            ""bindingGroup"": ""CarKeyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""CameraController"",
            ""bindingGroup"": ""CameraController"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // HeroesController
        m_HeroesController = asset.FindActionMap("HeroesController", throwIfNotFound: true);
        m_HeroesController_MovementPlayerBase = m_HeroesController.FindAction("MovementPlayerBase", throwIfNotFound: true);
        m_HeroesController_JumpPlayerBase = m_HeroesController.FindAction("JumpPlayerBase", throwIfNotFound: true);
        // CarController
        m_CarController = asset.FindActionMap("CarController", throwIfNotFound: true);
        m_CarController_CarMovementBase = m_CarController.FindAction("CarMovementBase", throwIfNotFound: true);
        m_CarController_Exit = m_CarController.FindAction("Exit", throwIfNotFound: true);
        // CameraController
        m_CameraController = asset.FindActionMap("CameraController", throwIfNotFound: true);
        m_CameraController_CameraLook = m_CameraController.FindAction("CameraLook", throwIfNotFound: true);
        m_CameraController_Zoom = m_CameraController.FindAction("Zoom", throwIfNotFound: true);
    }

    ~@HeroMovement()
    {
        UnityEngine.Debug.Assert(!m_HeroesController.enabled, "This will cause a leak and performance issues, HeroMovement.HeroesController.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CarController.enabled, "This will cause a leak and performance issues, HeroMovement.CarController.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CameraController.enabled, "This will cause a leak and performance issues, HeroMovement.CameraController.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // HeroesController
    private readonly InputActionMap m_HeroesController;
    private List<IHeroesControllerActions> m_HeroesControllerActionsCallbackInterfaces = new List<IHeroesControllerActions>();
    private readonly InputAction m_HeroesController_MovementPlayerBase;
    private readonly InputAction m_HeroesController_JumpPlayerBase;
    /// <summary>
    /// Provides access to input actions defined in input action map "HeroesController".
    /// </summary>
    public struct HeroesControllerActions
    {
        private @HeroMovement m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public HeroesControllerActions(@HeroMovement wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "HeroesController/MovementPlayerBase".
        /// </summary>
        public InputAction @MovementPlayerBase => m_Wrapper.m_HeroesController_MovementPlayerBase;
        /// <summary>
        /// Provides access to the underlying input action "HeroesController/JumpPlayerBase".
        /// </summary>
        public InputAction @JumpPlayerBase => m_Wrapper.m_HeroesController_JumpPlayerBase;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_HeroesController; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="HeroesControllerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(HeroesControllerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="HeroesControllerActions" />
        public void AddCallbacks(IHeroesControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_HeroesControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HeroesControllerActionsCallbackInterfaces.Add(instance);
            @MovementPlayerBase.started += instance.OnMovementPlayerBase;
            @MovementPlayerBase.performed += instance.OnMovementPlayerBase;
            @MovementPlayerBase.canceled += instance.OnMovementPlayerBase;
            @JumpPlayerBase.started += instance.OnJumpPlayerBase;
            @JumpPlayerBase.performed += instance.OnJumpPlayerBase;
            @JumpPlayerBase.canceled += instance.OnJumpPlayerBase;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="HeroesControllerActions" />
        private void UnregisterCallbacks(IHeroesControllerActions instance)
        {
            @MovementPlayerBase.started -= instance.OnMovementPlayerBase;
            @MovementPlayerBase.performed -= instance.OnMovementPlayerBase;
            @MovementPlayerBase.canceled -= instance.OnMovementPlayerBase;
            @JumpPlayerBase.started -= instance.OnJumpPlayerBase;
            @JumpPlayerBase.performed -= instance.OnJumpPlayerBase;
            @JumpPlayerBase.canceled -= instance.OnJumpPlayerBase;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="HeroesControllerActions.UnregisterCallbacks(IHeroesControllerActions)" />.
        /// </summary>
        /// <seealso cref="HeroesControllerActions.UnregisterCallbacks(IHeroesControllerActions)" />
        public void RemoveCallbacks(IHeroesControllerActions instance)
        {
            if (m_Wrapper.m_HeroesControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="HeroesControllerActions.AddCallbacks(IHeroesControllerActions)" />
        /// <seealso cref="HeroesControllerActions.RemoveCallbacks(IHeroesControllerActions)" />
        /// <seealso cref="HeroesControllerActions.UnregisterCallbacks(IHeroesControllerActions)" />
        public void SetCallbacks(IHeroesControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_HeroesControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HeroesControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="HeroesControllerActions" /> instance referencing this action map.
    /// </summary>
    public HeroesControllerActions @HeroesController => new HeroesControllerActions(this);

    // CarController
    private readonly InputActionMap m_CarController;
    private List<ICarControllerActions> m_CarControllerActionsCallbackInterfaces = new List<ICarControllerActions>();
    private readonly InputAction m_CarController_CarMovementBase;
    private readonly InputAction m_CarController_Exit;
    /// <summary>
    /// Provides access to input actions defined in input action map "CarController".
    /// </summary>
    public struct CarControllerActions
    {
        private @HeroMovement m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CarControllerActions(@HeroMovement wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CarController/CarMovementBase".
        /// </summary>
        public InputAction @CarMovementBase => m_Wrapper.m_CarController_CarMovementBase;
        /// <summary>
        /// Provides access to the underlying input action "CarController/Exit".
        /// </summary>
        public InputAction @Exit => m_Wrapper.m_CarController_Exit;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CarController; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CarControllerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CarControllerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CarControllerActions" />
        public void AddCallbacks(ICarControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_CarControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CarControllerActionsCallbackInterfaces.Add(instance);
            @CarMovementBase.started += instance.OnCarMovementBase;
            @CarMovementBase.performed += instance.OnCarMovementBase;
            @CarMovementBase.canceled += instance.OnCarMovementBase;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CarControllerActions" />
        private void UnregisterCallbacks(ICarControllerActions instance)
        {
            @CarMovementBase.started -= instance.OnCarMovementBase;
            @CarMovementBase.performed -= instance.OnCarMovementBase;
            @CarMovementBase.canceled -= instance.OnCarMovementBase;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CarControllerActions.UnregisterCallbacks(ICarControllerActions)" />.
        /// </summary>
        /// <seealso cref="CarControllerActions.UnregisterCallbacks(ICarControllerActions)" />
        public void RemoveCallbacks(ICarControllerActions instance)
        {
            if (m_Wrapper.m_CarControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CarControllerActions.AddCallbacks(ICarControllerActions)" />
        /// <seealso cref="CarControllerActions.RemoveCallbacks(ICarControllerActions)" />
        /// <seealso cref="CarControllerActions.UnregisterCallbacks(ICarControllerActions)" />
        public void SetCallbacks(ICarControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_CarControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CarControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CarControllerActions" /> instance referencing this action map.
    /// </summary>
    public CarControllerActions @CarController => new CarControllerActions(this);

    // CameraController
    private readonly InputActionMap m_CameraController;
    private List<ICameraControllerActions> m_CameraControllerActionsCallbackInterfaces = new List<ICameraControllerActions>();
    private readonly InputAction m_CameraController_CameraLook;
    private readonly InputAction m_CameraController_Zoom;
    /// <summary>
    /// Provides access to input actions defined in input action map "CameraController".
    /// </summary>
    public struct CameraControllerActions
    {
        private @HeroMovement m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CameraControllerActions(@HeroMovement wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CameraController/CameraLook".
        /// </summary>
        public InputAction @CameraLook => m_Wrapper.m_CameraController_CameraLook;
        /// <summary>
        /// Provides access to the underlying input action "CameraController/Zoom".
        /// </summary>
        public InputAction @Zoom => m_Wrapper.m_CameraController_Zoom;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CameraController; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CameraControllerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CameraControllerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CameraControllerActions" />
        public void AddCallbacks(ICameraControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraControllerActionsCallbackInterfaces.Add(instance);
            @CameraLook.started += instance.OnCameraLook;
            @CameraLook.performed += instance.OnCameraLook;
            @CameraLook.canceled += instance.OnCameraLook;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CameraControllerActions" />
        private void UnregisterCallbacks(ICameraControllerActions instance)
        {
            @CameraLook.started -= instance.OnCameraLook;
            @CameraLook.performed -= instance.OnCameraLook;
            @CameraLook.canceled -= instance.OnCameraLook;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CameraControllerActions.UnregisterCallbacks(ICameraControllerActions)" />.
        /// </summary>
        /// <seealso cref="CameraControllerActions.UnregisterCallbacks(ICameraControllerActions)" />
        public void RemoveCallbacks(ICameraControllerActions instance)
        {
            if (m_Wrapper.m_CameraControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CameraControllerActions.AddCallbacks(ICameraControllerActions)" />
        /// <seealso cref="CameraControllerActions.RemoveCallbacks(ICameraControllerActions)" />
        /// <seealso cref="CameraControllerActions.UnregisterCallbacks(ICameraControllerActions)" />
        public void SetCallbacks(ICameraControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CameraControllerActions" /> instance referencing this action map.
    /// </summary>
    public CameraControllerActions @CameraController => new CameraControllerActions(this);
    private int m_KeyboardingSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardingScheme
    {
        get
        {
            if (m_KeyboardingSchemeIndex == -1) m_KeyboardingSchemeIndex = asset.FindControlSchemeIndex("Keyboarding");
            return asset.controlSchemes[m_KeyboardingSchemeIndex];
        }
    }
    private int m_CarKeyboardSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme CarKeyboardScheme
    {
        get
        {
            if (m_CarKeyboardSchemeIndex == -1) m_CarKeyboardSchemeIndex = asset.FindControlSchemeIndex("CarKeyboard");
            return asset.controlSchemes[m_CarKeyboardSchemeIndex];
        }
    }
    private int m_CameraControllerSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme CameraControllerScheme
    {
        get
        {
            if (m_CameraControllerSchemeIndex == -1) m_CameraControllerSchemeIndex = asset.FindControlSchemeIndex("CameraController");
            return asset.controlSchemes[m_CameraControllerSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "HeroesController" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="HeroesControllerActions.AddCallbacks(IHeroesControllerActions)" />
    /// <seealso cref="HeroesControllerActions.RemoveCallbacks(IHeroesControllerActions)" />
    public interface IHeroesControllerActions
    {
        /// <summary>
        /// Method invoked when associated input action "MovementPlayerBase" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMovementPlayerBase(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JumpPlayerBase" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJumpPlayerBase(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CarController" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CarControllerActions.AddCallbacks(ICarControllerActions)" />
    /// <seealso cref="CarControllerActions.RemoveCallbacks(ICarControllerActions)" />
    public interface ICarControllerActions
    {
        /// <summary>
        /// Method invoked when associated input action "CarMovementBase" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCarMovementBase(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Exit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnExit(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CameraController" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CameraControllerActions.AddCallbacks(ICameraControllerActions)" />
    /// <seealso cref="CameraControllerActions.RemoveCallbacks(ICameraControllerActions)" />
    public interface ICameraControllerActions
    {
        /// <summary>
        /// Method invoked when associated input action "CameraLook" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Zoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnZoom(InputAction.CallbackContext context);
    }
}
